apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default
resources:
  - ConfigMap.yaml
  - Deployment.yaml
  - Ingress.yaml
  - RoleAndRoleBining.yaml
  - Service.yaml
  - ServiceAccount.yaml

labels:
  - pairs:
      app: homepage
    includeSelectors: true