apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deploy.yml
  - service.yml
  - ingress.yml
  - pv.yml
  - pvc.yml
  - configmap.yml

# configMapGenerator:
#   - name: n8n-config
#     envs:
#       - n8n.env

# generatorOptions:
#   labels:
#     app: n8n

labels:
  - pairs:
      app: n8n
    includeSelectors: true
