apiVersion: v1
kind: Service
metadata:
  name: n8n-service
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/path:   /
    prometheus.io/port:   '8080'
spec:
  type: ClusterIP
  selector:
    app: n8n
  ports:
    - name: n8n-ui
      protocol: TCP
      port: 80
      targetPort: 5678