apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - volume.yaml
  - serviceAccount.yaml


labels:
  - pairs:
      app: jenkins
    includeSelectors: true
