apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kestra-ingress
spec:
  rules:
    - host: kestra.localhost
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: kestra-service
                port:
                  number: 80